version: '2'

services:
    php:
      container_name: php
      environment:
          XDEBUG_REMOTE_HOST_IP: docker.for.mac.localhost
      build: .docker/php
      ports:
          - 9000:9000
      depends_on:
          - mysql
      volumes:
          - .:/var/www/html:cached
          - .docker/php/conf/php.ini:/usr/local/etc/php/php.ini

    nginx:
      container_name: nginx
      build: .docker/nginx
      ports:
          - 80:80
          - 443:443
      volumes_from:
          - php
      volumes:
          - .docker/nginx/conf.d:/etc/nginx/conf.d
          - .docker/nginx/conf/nginx.config:/etc/nginx/nginx.conf
      depends_on:
          - php
      links:
          - php

    mysql:
      container_name: mysql
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: symf0ny
        MYSQL_HOST: 127.0.0.1
      ports:
        - "3333:3306"

    redis:
      container_name: redis
      image: redis
      ports:
        - "6379:6379"
      volumes:
        - ./var/data/redis:/data/redis